name: piggybanx
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.5.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  firebase_core: ^0.4.0+1
  firebase_auth: 0.15.3+1
  cloud_firestore: ^0.11.0+2
  flutter_redux: ^0.5.3
  flutter_webview_plugin: ^0.3.0+2
  audioplayers: ^0.13.2
  vibration: ^1.2.2
  http: ^0.12.0+1
  connectivity: ^0.4.2
  rxdart: ^0.21.0
  shared_preferences: ^0.5.3+4
  firebase_messaging: ^5.0.1+1
  provider: ^3.1.0+1
  get_it: ^3.0.3
  json_serializable: ^3.2.5
  flare_flutter: ^1.7.3
  video_player: ^0.10.5
  google_sign_in: 4.0.6
  font_awesome_flutter: ^8.5.0

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2


dev_dependencies:
  build_runner: ^1.0.0
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/coin.png
    - lib/assets/images/piggy_nyito.png
    - assets/coin_sound.mp3
    - lib/assets/animation/animation-piggy.gif
    - assets/locale/en.json
    - assets/piggy_etetes.flr
    - assets/locale/hu.json
    - assets/coin_sound.mp3
    - assets/animations/Baby-LevelUp.gif
    - assets/animations/Baby-Feed1.gif
    - assets/animations/Baby-Feed2.gif
    - assets/animations/Baby-Feed3.gif
    - assets/animations/Baby-Feed4.gif
    - assets/images/Baby-Normal.png
    - assets/images/adult_profile_4K.png
    - assets/animations/Baby-Sleep.gif
    - assets/animations/Child-LevelUp.gif
    - assets/animations/Child-Feed1.gif
    - assets/animations/Child-Feed2.gif
    - assets/animations/Child-Feed3.gif
    - assets/animations/Child-Feed4.gif
    - assets/animations/Child-Normal.gif
    - assets/animations/Child-Sleep.gif
    - assets/animations/Teen-LevelUp.gif
    - assets/animations/Teen-Feed1.gif
    - assets/animations/Teen-Feed2.gif
    - assets/animations/Teen-Feed3.gif
    - assets/animations/Teen-Feed4.gif
    - assets/animations/Teen-Normal.gif
    - assets/animations/Teen-Sleep.gif
    - assets/animations/coin.gif
    - assets/coin.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/assets/fonts/Montserrat-Regular.ttf
        - asset: lib/assets/fonts/Montserrat-Bold.ttf
        - asset: lib/assets/fonts/Montserrat-ExtraBold.ttf
          #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
